spring:
  application:
    name: PhysicalTrack
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/physical_track?characterEncoding=UTF-8
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
server:
  port: 80

# Privacy Keys
jwt:
  secret: BE8MUV2fMftsDZJ9bd3dvHsS7GEAursVqfBWq9mPYJksb7uTLocByox8Ui0A90Pi
  expiration: 31557600000000      # 1000년 ?